site_name: Software Supply Chain Security Notes
site_author: Hare Krishna Rai
site_description: >-
  A comprehensive resource for understanding and implementing software supply chain security.
repo_url: https://github.com/harekrishnarai/software-supply-chain-security-notes
repo_name: GitHub
nav:
  - Home: index.md
  - Introduction:
      - Overview: content/introduction/overview.md
      - Terminology: content/introduction/terminology.md
  - Risk Assessment:
      - Threat Modeling: content/risk-assessment/threat-modeling.md
      - Vulnerability Management: content/risk-assessment/vulnerability-management.md
  - Secure Development:
      - Dependency Management: content/secure-development/dependency-management.md
      - SBOM: content/secure-development/sbom.md
      - Secure Coding: content/secure-development/secure-coding.md
  - CI/CD Security:
      - Pipeline Security: content/ci-cd-security/pipeline-security.md
      - Artifact Signing: content/ci-cd-security/artifact-signing.md
  - Tools:
      - Scanners: content/tools/scanners.md
      - Monitoring: content/tools/monitoring.md
  - Best Practices:
      - Standards: content/best-practices/standards.md
      - Frameworks: content/best-practices/frameworks.md
extra_css:
  - assets/extra.css
extra_javascript:
  - assets/extra.js
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - tables
  - attr_list
plugins:
  - search
