site_name: Software Supply Chain Security Notes
site_author: Hare Krishna Rai
site_description: >-
  A comprehensive resource for understanding and implementing software supply chain security.
repo_url: https://github.com/harekrishnarai/software-supply-chain-security-notes
repo_name: GitHub
copyright: '© 2023-2025 Software Supply Chain Security'

nav:
  - Home: index.md
  - Introduction:
      - Overview: introduction/overview.md
      - Terminology: introduction/terminology.md
  - Risk Assessment:
      - Threat Modeling: risk-assessment/threat-modeling.md
      - Vulnerability Management: risk-assessment/vulnerability-management.md
  - Secure Development:
      - Dependency Management: secure-development/dependency-management.md
      - SBOM: secure-development/sbom.md
      - Secure Coding: secure-development/secure-coding.md
  - CI/CD Security:
      - Pipeline Security: ci-cd-security/pipeline-security.md
      - Artifact Signing: ci-cd-security/artifact-signing.md
  - Tools:
      - Scanners: tools/scanners.md
      - Monitoring: tools/monitoring.md
  - Best Practices:
      - Standards: best-practices/standards.md
      - Frameworks: best-practices/frameworks.md

extra_css:
  - assets/extra.css
  - assets/header-style.css
  - assets/visibility-fix.css
  - assets/home-style.css

extra_javascript:
  - assets/extra.js

theme:
  name: material
  palette:
    # Light mode (default)
    - scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/shield-lock
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: cyan
      accent: deep orange
      toggle:
        icon: material/shield-lock-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: JetBrains Mono
  icon:
    logo: material/security-network
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.expand
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - header.autohide
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - tags
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - minify:
      minify_html: true

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/harekrishnarai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/harekrishnarai
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your preferences and analyze site traffic.
      We never collect any personal data or information other than technical data for performance.
